# Generated by Django 2.2 on 2020-05-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('I', 'In Progress'), ('C', 'Completed')], max_length=1)),
            ],
        ),
    ]
