# Generated by Django 2.2 on 2020-05-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clists', '0002_checklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckList',
        ),
    ]
