# Generated by Django 2.2 on 2020-05-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clists', '0003_delete_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clists.Items')),
            ],
        ),
    ]
