# Generated by Django 2.2 on 2020-05-22 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clists', '0004_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
