# Generated by Django 2.2 on 2020-05-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clists', '0005_checklist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
