# Generated by Django 2.2 on 2020-05-26 08:37
# field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='clists.CheckList'),

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clists', '0006_auto_20200524_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='items',
        ),
        migrations.AddField(
            model_name='items',
            name='clist_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clists.CheckList'),
            preserve_default=False,
        ),
    ]
