# Generated by Django 2.2 on 2020-05-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clists', '0007_auto_20200526_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='clist_title',
            new_name='title',
        ),
    ]
