# Generated by Django 2.2 on 2020-05-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clists', '0010_items_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='title',
        ),
    ]
