# Generated by Django 2.2 on 2020-05-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clists', '0011_remove_items_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clists.CheckList'),
        ),
    ]
