# Generated by Django 2.2 on 2020-05-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clists', '0012_items_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('items', 'title')},
        ),
    ]
