# Generated by Django 2.2 on 2020-05-26 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clists', '0013_auto_20200526_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clists.CheckList'),
        ),
    ]
